-- Phase 38 contract UAT bootstrap.
-- Rehydrates the Contract Workspace with deterministic UAT contracts when the
-- live Supabase contracts table is empty or missing the contract mainline seed.

with refs as (
  select
    (select id from public.profiles where email = 'legal_manager@poly-gamma.com' limit 1) as legal_user_id,
    (select id from public.publishers where name = '233' limit 1) as publisher_233_id,
    (select id from public.publishers where name = 'LOFTER' limit 1) as publisher_lofter_id,
    (select id from public.advertisers where name = 'Daily Yoga' limit 1) as advertiser_daily_yoga_id
)
insert into public.contracts (
  id,
  object_type,
  object_id,
  contract_name,
  counterparty,
  owner_user_id,
  status,
  effective_date,
  expiry_date,
  metadata,
  created_by,
  updated_by
)
select
  contract_seed.id,
  contract_seed.object_type,
  contract_seed.object_id,
  contract_seed.contract_name,
  contract_seed.counterparty,
  refs.legal_user_id,
  contract_seed.status,
  contract_seed.effective_date,
  contract_seed.expiry_date,
  jsonb_strip_nulls(
    jsonb_build_object(
      'contract_no', contract_seed.contract_name,
      'contract_type', contract_seed.contract_type,
      'counterparty_name', contract_seed.counterparty,
      'publisher_id', contract_seed.publisher_id,
      'advertiser_id', contract_seed.advertiser_id,
      'owner_role', 'legal_manager',
      'requested_by_role', contract_seed.requested_by_role,
      'risk_level', contract_seed.risk_level,
      'currency', contract_seed.currency,
      'value_amount', contract_seed.value_amount,
      'blocker', contract_seed.blocker,
      'next_action', contract_seed.next_action,
      'finance_notes', contract_seed.finance_notes,
      'signed_at', contract_seed.signed_at,
      'archived_at', contract_seed.archived_at
    )
  ),
  refs.legal_user_id,
  refs.legal_user_id
from refs
cross join lateral (
  values
    (
      '11111111-1111-4111-8111-111111111001'::uuid,
      'publisher',
      refs.publisher_233_id,
      'CON-001',
      '233',
      'publisher_framework',
      refs.publisher_233_id::text,
      null::text,
      'legal_review',
      'media_director',
      'medium',
      'USD',
      8731::numeric,
      '2026-07-01'::date,
      '2027-06-30'::date,
      'Data processing clause needs Legal approval.',
      'Approve legal review or send redline.',
      null::text,
      null::text,
      null::text
    ),
    (
      '11111111-1111-4111-8111-111111111002'::uuid,
      'advertiser',
      refs.advertiser_daily_yoga_id,
      'CON-002',
      'Daily Yoga',
      'advertiser_msa',
      null::text,
      refs.advertiser_daily_yoga_id::text,
      'finance_review',
      'sales_director',
      'low',
      'USD',
      20000::numeric,
      '2026-07-01'::date,
      '2026-09-30'::date,
      'Finance needs to verify payment terms.',
      'Finance review payment terms.',
      null::text,
      null::text,
      null::text
    ),
    (
      '11111111-1111-4111-8111-111111111003'::uuid,
      'publisher',
      refs.publisher_233_id,
      'CON-003',
      '233',
      'settlement_side_letter',
      refs.publisher_233_id::text,
      null::text,
      'redline',
      'finance_manager',
      'high',
      'USD',
      8024::numeric,
      '2026-07-18'::date,
      null::date,
      'Settlement dispute adjustment needs counterparty acceptance.',
      'Resolve redline before signing.',
      'Adjustment amount must match final settlement confirmation.',
      null::text,
      null::text
    ),
    (
      '11111111-1111-4111-8111-111111111004'::uuid,
      'publisher',
      refs.publisher_lofter_id,
      'CON-004',
      'LOFTER',
      'publisher_framework',
      refs.publisher_lofter_id::text,
      null::text,
      'signed',
      'media_director',
      'medium',
      'USD',
      15000::numeric,
      '2026-06-15'::date,
      '2027-06-14'::date,
      null::text,
      'Archive signed contract.',
      null::text,
      '2026-06-20T10:00:00.000Z',
      null::text
    )
) as contract_seed(
  id,
  object_type,
  object_id,
  contract_name,
  counterparty,
  contract_type,
  publisher_id,
  advertiser_id,
  status,
  requested_by_role,
  risk_level,
  currency,
  value_amount,
  effective_date,
  expiry_date,
  blocker,
  next_action,
  finance_notes,
  signed_at,
  archived_at
)
on conflict (id) do update set
  object_type = excluded.object_type,
  object_id = excluded.object_id,
  contract_name = excluded.contract_name,
  counterparty = excluded.counterparty,
  owner_user_id = excluded.owner_user_id,
  status = excluded.status,
  effective_date = excluded.effective_date,
  expiry_date = excluded.expiry_date,
  metadata = excluded.metadata,
  updated_by = excluded.updated_by,
  updated_at = now();
